# Generated by Django 6.0 on 2025-12-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('breast_probability', models.FloatField()),
                ('breast_diagnosis', models.CharField(max_length=50)),
                ('breast_class', models.IntegerField()),
                ('liver_probability', models.FloatField()),
                ('liver_diagnosis', models.CharField(max_length=50)),
                ('liver_class', models.IntegerField()),
                ('lung_probability', models.FloatField()),
                ('lung_diagnosis', models.CharField(max_length=50)),
                ('lung_class', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
